"""remove user roles

Revision ID: 1c0d041af97a
Revises: cc6e7da347b1
Create Date: 2026-06-11 14:45:11.407535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0d041af97a'
down_revision: Union[str, Sequence[str], None] = 'cc6e7da347b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=8), nullable=False))
    # ### end Alembic commands ###
